spring.application.name=bookease

spring.datasource.url=jdbc:postgresql://localhost:5432/bookease
spring.datasource.username=bookease
spring.datasource.password=bookease123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:db/migration

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=bookease
spring.rabbitmq.password=bookease123

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}